version: '3.9'


services:
  test_db:
    container_name: test
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - '5435:5432'
    volumes:
      - ./data:/var/lib/postgresql/data